#!/bin/sh
#
# Copyright (C) 2022 Sing Yu Chan <i@pexcn.me>
#
# This is free software, licensed under the GNU General Public License v3.
# See /LICENSE for more information.
#

TRANSTUNNEL_NAME="${0##*/}"
TRANSTUNNEL_VERSION=0.1.0

TRANSTUNNEL_PREFIX_IPTABLES="TRANSTUNNEL_"
TRANSTUNNEL_PREFIX_IPSET="transtunnel_"

TRANSTUNNEL_SRC_DIRECT=transtunnel_src_direct
TRANSTUNNEL_SRC_PROXY=transtunnel_src_proxy
TRANSTUNNEL_SRC_NORMAL=transtunnel_src_normal
TRANSTUNNEL_DST_DIRECT=transtunnel_dst_direct
TRANSTUNNEL_DST_PROXY=transtunnel_dst_proxy
TRANSTUNNEL_DST_SPECIAL=transtunnel_dst_special

_print_usage() {
  cat << EOF
$TRANSTUNNEL_NAME $TRANSTUNNEL_VERSION
A bridge of linux and transparent tunnel proxy.

USAGE:
    $TRANSTUNNEL_NAME [OPTIONS]

OPTIONS:
    -t, --tun-name       [TODO]...
        --src-direct     Specify one or more source ip lists, outbound traffic from these ips
                         will be directly connected.
        --src-proxy      Specify one or more source ip lists, outbound traffic from these ips
                         will be pass through proxy.
        --src-normal     Specify one or more source ip lists, outbound traffic from these ips
                         will decide whether to pass through proxy according to the destination
                         ip lists.
        --dst-direct     Specify one or more destination ip lists, these ips will be directly
                         connected.
        --dst-proxy      Specify one or more destination ip lists, these ips will be pass
                         through proxy.
        --src-default    Default action for inbound traffic, available values: DIRECT, PROXY, NORMAL.
        --dst-default    Default action for outbound traffic, available values: DIRECT, PROXY.
        --self-proxy     Make local traffic pass through proxy, default as gateway only.
    -s, --server         Specify one or more ip addresses of the remote server, local and server
                         traffic will be directly connected.
    -i, --interface      Apply to specified network interface.
    -e, --extra          The specified parameters will be append to iptables.
    -m, --mark           Bypass outbound traffic with SO_MARK as specified value, it's a workaround
                         when the remote server doesn't have a static ip address.
                         [NOTE]: Not all clients support setting SO_MARK, and there may be
                         performance issues.
    -v, --verbose        Enable verbose logging.
    -f, --flush          Flush $TRANSTUNNEL_NAME rules then exit.
    -h, --help           Show this help message then exit.
EOF
}

_add_prefix() {
  sed "s/^/$1/"
}

_remove_empty() {
  sed '/^[[:space:]]*$/d'
}

_remove_comment() {
  sed '/^#/d'
}

_trim() {
  awk '{$1=$1};1'
}

_split_by_space() {
  [ -n "$1" ] || return 0
  echo "$1" | tr ',' ' '
}

_splice_content() {
  [ -n "$1" ] || return 0
  for file in $(_split_by_space "$1"); do cat $file; done
}

_apply_sysctl() {
  [ $(sysctl -n "$1") != "$2" ] && sysctl -wq "$1"="$2"
}

_get_reserved_ip() {
  cat <<- EOF
	0.0.0.0/8
	10.0.0.0/8
	100.64.0.0/10
	127.0.0.0/8
	169.254.0.0/16
	172.16.0.0/12
	192.0.0.0/24
	192.0.2.0/24
	192.31.196.0/24
	192.52.193.0/24
	192.88.99.0/24
	192.168.0.0/16
	192.175.48.0/24
	198.18.0.0/15
	198.51.100.0/24
	203.0.113.0/24
	224.0.0.0/4
	240.0.0.0/4
	255.255.255.255
	EOF
}

_get_special_ip() {
  echo $SERVER_IPS | tr ',' '\n' | grep -Eo "^([0-9]{1,3}\.){3}[0-9]{1,3}"
  ip route get 8.8.8.8 | sed 's/^.*src \([^ ]*\).*$/\1/;q'
}

_get_time() {
  date '+%Y-%m-%d %T'
}

debug() {
  [ "$VERBOSE" = 1 ] || return 0
  local time=$(_get_time)
  printf "[${time}] [DEBUG]: %s\n" "$*"
}

info() {
  local green='\e[0;32m'
  local clear='\e[0m'
  local time=$(_get_time)
  printf "${green}[${time}] [INFO]: ${clear}%s\n" "$*"
}

warn() {
  local yellow='\e[1;33m'
  local clear='\e[0m'
  local time=$(_get_time)
  printf "${yellow}[${time}] [WARN]: ${clear}%s\n" "$*" >&2
}

error() {
  local red='\e[0;31m'
  local clear='\e[0m'
  local time=$(_get_time)
  printf "${red}[${time}] [ERROR]: ${clear}%s\n" "$*" >&2
}

generate_ipset_rules() {
  _splice_content $SRC_DIRECT_FILES | _remove_empty | _remove_comment | _trim | _add_prefix "add $TRANSTUNNEL_SRC_DIRECT "
  _splice_content $SRC_PROXY_FILES | _remove_empty | _remove_comment | _trim | _add_prefix "add $TRANSTUNNEL_SRC_PROXY "
  _splice_content $SRC_NORMAL_FILES | _remove_empty | _remove_comment | _trim | _add_prefix "add $TRANSTUNNEL_SRC_NORMAL "
  _splice_content $DST_DIRECT_FILES | _remove_empty | _remove_comment | _trim | _add_prefix "add $TRANSTUNNEL_DST_DIRECT "
  _splice_content $DST_PROXY_FILES | _remove_empty | _remove_comment | _trim | _add_prefix "add $TRANSTUNNEL_DST_PROXY "
  _get_reserved_ip | _remove_empty | _remove_comment | _trim | _add_prefix "add $TRANSTUNNEL_DST_SPECIAL "
  _get_special_ip | _remove_empty | _remove_comment | _trim | _add_prefix "add $TRANSTUNNEL_DST_SPECIAL "
}

create_transtunnel_chain() {
  iptables-restore -n <<- EOF
	*mangle

	:TRANSTUNNEL_SRC_PREPARE - [0:0]
	:TRANSTUNNEL_SRC_AC - [0:0]
	:TRANSTUNNEL_DST_AC - [0:0]
	:TRANSTUNNEL_DST_FORWARD - [0:0]

	# PREPARE
	-A TRANSTUNNEL_SRC_PREPARE -m set --match-set $TRANSTUNNEL_DST_SPECIAL dst -j RETURN
	-A TRANSTUNNEL_SRC_PREPARE $IPT_EXTRAS -j TRANSTUNNEL_SRC_AC

	# SRC
	-A TRANSTUNNEL_SRC_AC -m set --match-set $TRANSTUNNEL_SRC_DIRECT src -j RETURN
	-A TRANSTUNNEL_SRC_AC -m set --match-set $TRANSTUNNEL_SRC_PROXY src -j TRANSTUNNEL_DST_FORWARD
	-A TRANSTUNNEL_SRC_AC -m set --match-set $TRANSTUNNEL_SRC_NORMAL src -j TRANSTUNNEL_DST_AC
	-A TRANSTUNNEL_SRC_AC -j ${SRC_DEFAULT:=TRANSTUNNEL_DST_AC}

	# DST
	-A TRANSTUNNEL_DST_AC -m set --match-set $TRANSTUNNEL_DST_DIRECT dst -j RETURN
	-A TRANSTUNNEL_DST_AC -m set --match-set $TRANSTUNNEL_DST_PROXY dst -j TRANSTUNNEL_DST_FORWARD
	-A TRANSTUNNEL_DST_AC -j ${DST_DEFAULT:=TRANSTUNNEL_DST_FORWARD}

	# TUN
	-A TRANSTUNNEL_DST_FORWARD -j MARK --set-mark 1

	COMMIT
	EOF
  debug "$TRANSTUNNEL_NAME chain created."
}

apply_transtunnel_rules() {
  if [ -z "$INTERFACES" ]; then
    iptables -t mangle -I PREROUTING 1 -j TRANSTUNNEL_SRC_PREPARE
    debug "$TRANSTUNNEL_NAME rules applied."
  else
    for interface in $(_split_by_space $INTERFACES); do
      iptables -t mangle -I PREROUTING 1 -i $interface -j TRANSTUNNEL_SRC_PREPARE
      debug "$TRANSTUNNEL_NAME rules apply to $interface interface."
    done
  fi
}

apply_self_proxy_rules() {
  iptables -t mangle -N TRANSTUNNEL_DST_PREPARE
  iptables -t mangle -A TRANSTUNNEL_DST_PREPARE -m set --match-set $TRANSTUNNEL_DST_SPECIAL dst -j RETURN

  # negate matching in non-[DIRECT|PROXY] mode
  [ "$DST_DEFAULT" = "RETURN" ] || iptables -t mangle -A TRANSTUNNEL_DST_PREPARE -m set --match-set $TRANSTUNNEL_DST_DIRECT dst -j RETURN
  [ "$DST_DEFAULT" = "TRANSTUNNEL_DST_FORWARD" ] || iptables -t mangle -A TRANSTUNNEL_DST_PREPARE -m set --match-set $TRANSTUNNEL_DST_PROXY dst $IPT_EXTRAS -j MARK --set-mark 1

  # avoid traffic loopback issues, reference: https://github.com/v2ray/v2ray-core/issues/2621
  [ -z "$DIRECT_MARK" ] || iptables -t mangle -A TRANSTUNNEL_DST_PREPARE -m mark --mark $DIRECT_MARK -j RETURN

  # only makes sense in non-DIRECT mode
  if [ "$DST_DEFAULT" != "RETURN" ]; then
    iptables -t mangle -A TRANSTUNNEL_DST_PREPARE $IPT_EXTRAS -j MARK --set-mark 1
  fi

  iptables -t mangle -I OUTPUT 1 -j TRANSTUNNEL_DST_PREPARE
  debug "$TRANSTUNNEL_NAME rules apply to self host."
}

# TODO: check if it works.
#apply_tcp_divert() {
#  iptables -t mangle -N TRANSTUNNEL_TCP_DIVERT
#  iptables -t mangle -A TRANSTUNNEL_TCP_DIVERT -j MARK --set-mark 1
#  iptables -t mangle -A TRANSTUNNEL_TCP_DIVERT -j ACCEPT
#  iptables -t mangle -I PREROUTING 1 -p tcp -m socket -j TRANSTUNNEL_TCP_DIVERT
#  debug "tcp divert rules optimized."
#}

prepare_environment() {
  # check environment
  modinfo xt_mark &>/dev/null || { error "xt_mark kernel module is not supported."; exit 1; }
  command -v ip >/dev/null || { error "ip command not found."; exit 1; }
  command -v ipset >/dev/null || { error "ipset command not found."; exit 1; }
  command -v iptables >/dev/null || { error "iptables command not found."; exit 1; }

  # TODO: check real required?
  # enable ip forward
  _apply_sysctl net.ipv4.ip_forward 1
  [ "$?" != 0 ] || warn "Requires net.ipv4.ip_forward=1, applied."
}

flush_rules() {
  iptables-save --counters | grep -v "$TRANSTUNNEL_PREFIX_IPTABLES" | iptables-restore --counters
  debug "iptables flushed."

  ip rule del fwmark 1 lookup 100 2>/dev/null
  ip route del default dev "$TUN_NAME" table 100 2>/dev/null
  ip route flush table 100 2>/dev/null
  debug "routes removed."

  for name in $(ipset -n list | grep "$TRANSTUNNEL_PREFIX_IPSET"); do
    ipset flush $name 2>/dev/null
    ipset destroy $name 2>/dev/null
    debug "ipset $name destroyed."
  done
  debug "ipsets destroyed."

  info "$TRANSTUNNEL_NAME rules flushed."
}

init_ipset() {
  ipset -exist restore <<- EOF
	create $TRANSTUNNEL_SRC_DIRECT hash:ip hashsize 64 family inet
	create $TRANSTUNNEL_SRC_PROXY hash:ip hashsize 64 family inet
	create $TRANSTUNNEL_SRC_NORMAL hash:ip hashsize 64 family inet
	create $TRANSTUNNEL_DST_DIRECT hash:net hashsize 64 family inet
	create $TRANSTUNNEL_DST_PROXY hash:net hashsize 64 family inet
	create $TRANSTUNNEL_DST_SPECIAL hash:net hashsize 64 family inet
	$(generate_ipset_rules)
	EOF
  info "ipsets created."
}

init_route() {
  ip rule add fwmark 1 lookup 100
  ip route add default dev "$TUN_NAME" table 100
  info "routes added."
}

init_iptables() {
  # create common transproxy chain for mangle table, it's required for both tcp and udp.
  create_transtunnel_chain
  # jump in from PREROUTING chain, make it works.
  apply_transtunnel_rules
  [ -z "$SELF_PROXY" ] || apply_self_proxy_rules
  #apply_tcp_divert
  info "iptables applied."
}

parse_args() {
  local args="$@"
  local args_num="$#"
  while [ "$#" -gt 0 ]; do
    case "$1" in
      -t|--tun-name)
        TUN_NAME="$2"
        shift 2
        ;;
      --src-direct)
        SRC_DIRECT_FILES="$2"
        shift 2
        ;;
      --src-proxy)
        SRC_PROXY_FILES="$2"
        shift 2
        ;;
      --src-normal)
        SRC_NORMAL_FILES="$2"
        shift 2
        ;;
      --dst-direct)
        DST_DIRECT_FILES="$2"
        shift 2
        ;;
      --dst-proxy)
        DST_PROXY_FILES="$2"
        shift 2
        ;;
      --src-default)
        case "$2" in
          direct|DIRECT) SRC_DEFAULT=RETURN;;
          proxy|PROXY) SRC_DEFAULT=TRANSTUNNEL_DST_FORWARD;;
          normal|NORMAL) SRC_DEFAULT=TRANSTUNNEL_DST_AC;;
          *) error "wrong option: $1 $2"; exit 2;;
        esac
        shift 2
        ;;
      --dst-default)
        case "$2" in
          direct|DIRECT) DST_DEFAULT=RETURN;;
          proxy|PROXY) DST_DEFAULT=TRANSTUNNEL_DST_FORWARD;;
          *) error "wrong option: $1 $2"; exit 2;;
        esac
        shift 2
        ;;
      --self-proxy)
        SELF_PROXY=1;
        shift 1
        ;;
      -s|--server)
        SERVER_IPS="$2"
        shift 2
        ;;
      -i|--interface)
        INTERFACES="$2"
        shift 2
        ;;
      -e|--extra)
        IPT_EXTRAS="$2"
        shift 2
        ;;
      -m|--mark)
        DIRECT_MARK="$2"
        shift 2
        ;;
      -v|--verbose)
        VERBOSE=1
        shift 1
        ;;
      -f|--flush)
        FLUSH=1
        shift 1
        ;;
      -h|--help)
        _print_usage
        exit 0
        ;;
      *)
        error "unknown option: $1"
        exit 2
        ;;
    esac
  done

  debug "received arguments: $args"
  [ -z "$TUN_NAME" ] || debug "TUN_NAME=$TUN_NAME"
  [ -z "$SRC_DIRECT_FILES" ] || debug "SRC_DIRECT_FILES=$SRC_DIRECT_FILES"
  [ -z "$SRC_PROXY_FILES" ] || debug "SRC_PROXY_FILES=$SRC_PROXY_FILES"
  [ -z "$SRC_NORMAL_FILES" ] || debug "SRC_NORMAL_FILES=$SRC_NORMAL_FILES"
  [ -z "$DST_DIRECT_FILES" ] || debug "DST_DIRECT_FILES=$DST_DIRECT_FILES"
  [ -z "$DST_PROXY_FILES" ] || debug "DST_PROXY_FILES=$DST_PROXY_FILES"
  [ -z "$SRC_DEFAULT" ] || debug "SRC_DEFAULT=$SRC_DEFAULT"
  [ -z "$DST_DEFAULT" ] || debug "DST_DEFAULT=$DST_DEFAULT"
  [ -z "$SELF_PROXY" ] || debug "SELF_PROXY=$SELF_PROXY"
  [ -z "$SERVER_IPS" ] || debug "SERVER_IPS=$SERVER_IPS"
  [ -z "$INTERFACES" ] || debug "INTERFACES=$INTERFACES"
  [ -z "$IPT_EXTRAS" ] || debug "IPT_EXTRAS=$IPT_EXTRAS"
  [ -z "$DIRECT_MARK" ] || debug "DIRECT_MARK=$DIRECT_MARK"
  [ -z "$VERBOSE" ] || debug "VERBOSE=$VERBOSE"
  [ -z "$FLUSH" ] || debug "FLUSH=$FLUSH"

  if [ -n "$FLUSH" ]; then
    [ "$args_num" = 1 ] || warn "invalid arguments other than [-f|--flush]."
    prepare_environment
    flush_rules
    exit 0
  fi
  [ -n "$TUN_NAME" ] || { error "[-t|--tun-name] is required."; exit 2; }
  ! [ -z "$SERVER_IPS" -a -z "$DIRECT_MARK" ] || { error "[-s|--server] or [-m|--mark] is required."; exit 2; }
  ! [ -n "$SERVER_IPS" -a -n "$DIRECT_MARK" ] || warn "it is recommended to use one of [-s|--server] and [-m|--mark]."
}

parse_args "$@"
prepare_environment
flush_rules
init_ipset
init_route
init_iptables
